# Generated by Django 4.0.4 on 2022-04-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Padlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=15)),
                ('owner', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=25)),
                ('registration_time', models.CharField(max_length=20)),
                ('registered_by', models.CharField(max_length=20)),
            ],
        ),
    ]
